/*******************
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*******************/
#include <cstdlib>
#include <cstdio>
#include <exception>
#include <vector>
#include <algorithm>
#include <string>
#include <iostream>
#include <unordered_map>

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> table;
        for(auto c : s) {
            if(table.find(c) == table.end())
                table[c] = 1;
            else
                table[c]++;
        }
        char res;
        for(auto c : t) {
            if(table.find(c) == table.end())
                return c;
            else {
                --table[c];
                if(table[c] < 0) {
                    res = c;
                    break;
                }      
            }
        }
        return res;
    }
};

int main() {
    return 0;
}